name: Generate Status JSON

on:
  schedule:
    - cron: "0 * * * *"  # Rodar a cada hora
  push:
    branches:
      - main  # Rodar sempre que houver um push na branch principal

jobs:
  generate_status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate status JSON
      run: |
        echo '{
          "server_status": "online",
          "ping": "50ms",
          "latency": "20ms",
          "players_online": 0
        }' > status.json

    - name: Commit and push status.json
      run: |
        git config --global user.email "60338847+linwaru@users.noreply.github.com"
        git config --global user.name "Gyu Bot"
        git add status.json
        git commit -m "update status.json"
        git push
